### DISCUSSION TITLE
Is it possible to change the shape of the article thumbnails in the home page?

### DISCUSSION THREAD

**Discussion by javierfs** [HEIGE-PCloud/DoIt#179] [Q&A] [answered]
I was wondering if is possible to change the rectangle shape of the articles thumbnails in the homepage for a more minimalistic & rounded corners as the newsroom theme: https://jamstackthemes.dev/demo/theme/newsroom/

If so, how can I change it?

**Comment by HEIGE-PCloud** [comment, marked as answer]
You can add your own custom CSS by editing `your_site/assets/css/_custom.scss` to achieve this looking.

```css
.home[posts] .summary .featured-image-preview img.lazyloaded {
    border-radius: 25px;
}
```

will give you

![image](https://user-images.githubusercontent.com/52968553/129190151-66264479-afe9-4dfb-a193-f80b7562c0ed.png)

Make sure using the extended verion of Hugo to build the site for custom style to work.
