### DISCUSSION TITLE
修改页面宽度

### DISCUSSION THREAD

**Discussion by 9201314** [HEIGE-PCloud/DoIt#212] [Q&A] [answered]
不知道在哪里可以联系到作者，只能在这里开个issue，请见谅！
我对前端一窍不通，知道通过修改css可以改变页面宽度，但是不知道该修改哪里？
就想首页、归档页、about那些所有页面都能宽一些，和post一样。现在除了post，其他页面两边留白有些多，经常一行放不下内容，换行影响阅读和观感。
哪位大神有空点拨一下我吗？😫

**Comment by HEIGE-PCloud** [comment, marked as answer]
你可以在 `your_site/assets/css/_custom.scss` 中创建你的[自定义样式](https://hugodoit.pages.dev/zh-cn/theme-documentation-basics/#33-%E8%87%AA%E5%AE%9A%E4%B9%89%E6%A0%B7%E5%BC%8F)。

在该文件中添加以下 CSS 代码以修改页面宽度。DoIt 主题默认的页面宽度为 60%，你可以将其修改为你喜欢的数值。

需要注意的是，在页面排版中，页面不应该过窄，但也不应该过宽。过宽的页面会导致读者在换行时很难定位下一行的开头。因此，通过百分比控制页面宽度也并非万无一失。在宽屏、带鱼屏上，原先恰当的宽度会被按照百分比继续拉长，导致较差的阅读体验。通过设置 `max-width` 属性控制页面的最大宽度，可以保证在不同屏幕尺寸下的一致文字阅读体验。

```css
.page 
{
    width: 70%;
    max-width: 1000px;
}
```

对于分类、系列页面，通过以下 CSS 将每个栏目的宽度调为 100%。这可以使每行只显示一个栏目，让其中所包含的标题显示完整。

```css
.card-item
{
    width: 100% !important;
}
```

另外，你必须使用 extended 版本的 hugo 来生成你的站点以使自定义样式生效。

Reference: [自定义样式](https://hugodoit.pages.dev/zh-cn/theme-documentation-basics/#33-%E8%87%AA%E5%AE%9A%E4%B9%89%E6%A0%B7%E5%BC%8F)
