### DISCUSSION TITLE
[FEATURE] 如何在 config.toml 中配置评论系统，使其保持最新的版本？

### DISCUSSION THREAD

**Discussion by ghost** [HEIGE-PCloud/DoIt#303] [Q&A] [answered]
### 如何在 config.toml 中配置评论系统，使其保持最新的版本？
我看到当前引用的 js 库位于：src="/lib/waline/Waline.min.js"
但这个库不是最新的Waline官方版本，我想始终保持最新版本，我该如何在config.toml 中配置呢？

### Useful reference 有价值的参考
https://waline.js.org/guide/client/import.html#通过-cdn

**Comment by HEIGE-PCloud** [comment, marked as answer]
你可以配置 `your_site/assets/data/cdn/jsdelivr.yml` 并在 config.toml 中配置 `params.cdn` 选项指定你想使用的版本。

```toml
  # CDN config for third-party library files
  # 第三方库文件的 CDN 设置
  [params.cdn]
    # CDN data file name, disabled by default
    # ("jsdelivr.yml")
    # located in "themes/DoIt/assets/data/cdn/" directory
    # you can store your own data files in the same path under your project:
    # "assets/data/cdn/"
    # CDN 数据文件名称, 默认不启用
    # ("jsdelivr.yml")
    # 位于 "themes/DoIt/assets/data/cdn/" 目录
    # 可以在你的项目下相同路径存放你自己的数据文件:
    # "assets/data/cdn/"
    data = ""
```

在这里 https://github.com/HEIGE-PCloud/DoIt/blob/main/assets/data/cdn/jsdelivr.yml 查看默认的配置文件。

Reference: https://hugodoit.pages.dev/zh-cn/theme-documentation-basics/#site-configuration
