### DISCUSSION TITLE
Can I hide Author?

### DISCUSSION THREAD

**Discussion by TheDoubleH** [HEIGE-PCloud/DoIt#354] [Q&A] [answered]
Given that I am the only author on my blog, is there a setting to hide the Author on posts?

**Comment by HEIGE-PCloud** [comment, marked as answer]
Set your name to an empty space will "hide" it for you.

```toml
[author]
  name = " "
```

![image](https://user-images.githubusercontent.com/52968553/142279310-166b0930-7639-410c-b194-1fde74e38181.png)

**Reply by TheDoubleH** [reply]
I added 

```TOML
[author]
  name = " "
```

to my config.toml file - Worked like a charm!
