### DISCUSSION TITLE
Cannot get Google Analytics to work

### DISCUSSION THREAD

**Discussion by TheDoubleH** [HEIGE-PCloud/DoIt#374] [Q&A] [answered]
It's probably me, however I am unable to get google analytics to work

![image](https://user-images.githubusercontent.com/24259184/144800533-d3c13fd2-da28-4452-af5a-8c5e290fc6ad.png)

I have added my `googleAnalytics` to the `config.toml` file, however the created html does not have any content in the header.

What am I doing wrong?

**Comment by HEIGE-PCloud** [comment, marked as answer]
You can configure the Google Analytics in this way:

```toml
  [params.analytics]
    enable = false
    # Google Analytics
    [params.analytics.google]
      id = "your id here"
      # whether to anonymize IP
      anonymizeIP = true
```


Check out the sample configuration: https://hugodoit.pages.dev/theme-documentation-basics/#site-configuration
