### DISCUSSION TITLE
Enabling Gravitec

### DISCUSSION THREAD

**Discussion by TheDoubleH** [HEIGE-PCloud/DoIt#449] [Q&A] [answered]
Forgive me, but I am still new to Hugo.

I need to add 

`<script src="https://cdn.gravitec.net/storage/topsecretcodehere/client.js" async></script>`

to the `<head>` tag.

Been reading the hugo documentation, and that didn't clear it up for me, if I am able to do that. (in an easy way).

**Comment by eyllanesc** [comment, marked as answer]
@TheDoubleH  try with:

```toml
 [params.page.library.js] 
   gravitec = "https://cdn.gravitec.net/storage/topsecretcodehere/client.js" 
```

See:

https://github.com/HEIGE-PCloud/DoIt/blob/03a2f5e04e17a54d58643eb7e4d32fd404c825b0/exampleSite/config.toml#L955-L959

**Reply by TheDoubleH** [reply]
Worked like a charm! Thanks @eyllanesc 

Well - Almost. 

The script does come in, but in the <body> - AND the `async` isn't there. - That said - it DOES appear to work

**Reply by eyllanesc** [reply]
If async is mandatory then a possible solution is to create a script that injects the library: 

```toml
 [params.page.library.js] 
   gravitec_loader = "gravitec_loader.js" 
   # located in "assets/"
```

gravitec_loader.js
```js
// https://stackoverflow.com/a/18784960/6622587
const script = document.createElement('script')
script.src = 'https://cdn.gravitec.net/storage/topsecretcodehere/client.js' 
script.type = 'text/javascript'
script.async = true
document.head.appendChild(script);
```
