### ISSUE TITLE
[BUG] Unable to use Artalk（无法使用 Artalk）

### ISSUE THREAD

**Issue by ygxbnet** [HEIGE-PCloud/DoIt#1092]
### Describe the bug 描述你遇到的错误

我使用的使 main 分支 https://github.com/HEIGE-PCloud/DoIt/commit/731cfc9086f5d24b13fa577588e56ab577841815 最新版的 DoIt

然后使用了 Artalk 作为评论系统（如配置文件），但却无法使用。感觉不是我配置的问题，因为网页中根本没有加载 artalk 库（如截图）

网站：https://blog.ygxb.net

### Screenshots 屏幕截图

![image](https://github.com/HEIGE-PCloud/DoIt/assets/87907576/76b25442-f100-47cd-a220-5f6ff635f3db)

### Build Environment 构建环境

- **Build system**: `Vercel`
- **DoIt version**: https://github.com/HEIGE-PCloud/DoIt/commit/731cfc9086f5d24b13fa577588e56ab577841815
- **Hugo version**: `0.119.0`

### Preview Environment 预览环境

- **Browser:** `Edge`

### Additional Information 补充信息

```toml
# artalk 评论系统设置
[page.comment.artalk]
enable = true
server = "https://artalk.ygxb.net"
site = "Default Site"
lite = false
katex = false
lightbox = true
pageview = true
commentCount = true
```

> 源文件：https://github.com/ygxbnet/Blog/blob/b9546925cea6d767b8135277c0bc0808143b6841/hugo.toml#L142C1-L151C20

**Comment by ygxbnet** [comment]
我这几天又自己捣鼓了一下，发现好像是文档的问题，文档掉了一个 `params.`

这是文档的的配置：

```toml
# [artalk](https://artalk.js.org/) 评论系统设置
      [page.comment.artalk]
        enable = false
        server = ""
        site = ""
        lite = false
        katex = false
        lightbox = false
        pageview = true
        commentCount = true
```

正确配置应该如下：

```toml
# [artalk](https://artalk.js.org/) 评论系统设置
      [params.page.comment.artalk]
        enable = false
        server = ""
        site = ""
        lite = false
        katex = false
        lightbox = false
        pageview = true
        commentCount = true
```
