### ISSUE TITLE
[FEATURE] Indent two characters when writing in Chinese

### ISSUE THREAD

**Issue by kneep** [HEIGE-PCloud/DoIt#1113]
### Describe the feature you want 描述你的功能需求

Provide an option to indent two characters for the first line of each paragraph when writing in Chinese.

**Comment by HEIGE-PCloud** [comment]
Add 

```css
.content > p { 
    text-indent: 4ch;
}
```

to `_custom.scss` will do the trick.

**Comment by kneep** [comment]
> Add
> 
> ```css
> .content > p { 
>     text-indent: 4ch;
> }
> ```
> 
> to `_custom.scss` will do the trick.

Thanks. This snippet has subtle side effects, like, the inline code block being indented incorrectly:
<img width="620" alt="image" src="https://github.com/HEIGE-PCloud/DoIt/assets/525419/cb8e5693-8267-4ff0-9caf-456fff1dbbd8">

**Comment by 713b76b7-2247-4bd5-98a7-014226363f9b** [comment]
```css
.content > p {
    text-indent: 4ch;
}

.content > code {
    text-indent: 0;
}
```

**Comment by kneep** [comment]
> ```css
> .content > code {
>     text-indent: 0;
> }
> ```
This does not work.

**Comment by CXwudi** [comment]
Sorry for commenting in an old issue. This is my solution:

``` css
// _override.scss
.single {
  .content {
    >p {
      text-indent: 4ch;
    }
    > code {
      text-indent: 0;
    }
  }
}
```
And this is how it looks like:
![image](https://github.com/HEIGE-PCloud/DoIt/assets/17377423/6f73fb15-7de6-4a02-91e4-62a53bf49b12)

However, as you can see it also indents English post, wondering if it is possible to only indent the Chinese post
