### ISSUE TITLE
[BUG] The image refactor cause --disableFastRender not working 

### ISSUE THREAD

**Issue by TinoGuo** [HEIGE-PCloud/DoIt#1284]
### Describe the bug 描述你遇到的错误

When run `hugo server -D --disableFastRender`
it will cause the error as below
```
ERROR render of "term" failed: "/Users/blog/layouts/_default/baseof.html:81:12": execute of template failed: template: taxonomy/list.html:81:12: executing "taxonomy/list.html" at <partial "header.html" .>: error calling partial: "/Users/blog/themes/DoIt/layouts/partials/header.html:8:77": execute of template failed: template: partials/header.html:8:77: executing "partials/header.html" at <partial "plugin/image.html">: error calling partial: "/Users/blog/themes/DoIt/layouts/partials/plugin/image.html:29:43": execute of template failed: template: partials/plugin/image.html:29:43: executing "partials/plugin/image.html" at <site>: can't evaluate field cacheRemote in type string
```

### Expected behavior 期待的行为

Build successfully

### Screenshots 屏幕截图

NA

### Build Environment 构建环境

- OS: [macOS]
- Theme version/commit [0.4.0, dfc113a]
- Hugo version [0.126.1+extended]

### Preview Environment 预览环境

- OS: [macOS]

**Comment by TinoGuo** [comment]
It can occasionally happen in prod build as well. I build 4 times and got 1 time error
<img width="1356" alt="image" src="https://github.com/HEIGE-PCloud/DoIt/assets/4519784/3f8a0161-adf5-4236-935b-c5767a651882">

**Comment by HEIGE-PCloud** [comment]
Can you share your params.toml or hugo.toml configurations? Specifically have you configured anything about `params.image`?

**Comment by TinoGuo** [comment]
```yaml
image:
  # 缓存图片链接到本地
  cacheRemote : true
  # 图片缩放和优化
  optimise : true
```
I copied the configuration from master

**Comment by HEIGE-PCloud** [comment]
Can you provide a minimal reproduction? I cannot reproduce this issue on the exampleSite.

The error message is just saying that `params.image` has type `string` instead of `map`, which indicates that it might be a configuration error. I suspect somewhere in the config there is an `image = "some/image.png"` entry which is causing conflicts.

**Comment by TinoGuo** [comment]
I added `image : ""` into the seo.en.yaml, will it cause the conflict? as this is not 100% reproducible, so I need some time to make minimal project.

**Comment by TinoGuo** [comment]
I tried to log the data and debug the template, I found one interesting thing
| Status | ScreenShot | Type |
|--------|--------|--------|
| Success | <img width="1070" alt="Screenshot 2024-05-28 at 22 53 46" src="https://github.com/HEIGE-PCloud/DoIt/assets/4519784/8c006e6f-0eb4-491c-a76a-f03e295d9bd9"> | Map |
| Fail | <img width="1066" alt="Screenshot 2024-05-28 at 22 54 05" src="https://github.com/HEIGE-PCloud/DoIt/assets/4519784/a093c496-254e-4535-9544-f8e3e94d8866"> | empty string |
| Fail | <img width="1040" alt="Screenshot 2024-05-28 at 22 55 37" src="https://github.com/HEIGE-PCloud/DoIt/assets/4519784/b97c4fd7-b6e7-44f4-8db0-fb1e5e1dc28d"> | Map but recognize as String |

So it seems the data is not recoginze instead of configuration problem

btw, I'm using YAML to config hugo

**Comment by HEIGE-PCloud** [comment]
How do you trigger the third case? What's the difference between the first case and the third case?

This might be an issue with Hugo...

**Comment by TinoGuo** [comment]
I try to rename image in image.html
from
```html
{{- $cacheRemote := .CacheRemote | default site.Params.image.cacheRemote | default false -}}
{{- $optimise := .Optimise | default site.Params.image.optimise | default false -}}
```
to
```html
{{- $cacheRemote := .CacheRemote | default site.Params.imageX.cacheRemote | default false -}}
{{- $optimise := .Optimise | default site.Params.imageX.optimise | default false -}}
```
and config the imageX in the params.yaml, then no issue found, so it still could be conflict. however, I searched the config in my site, only this image was configured. I have no idea to continue. could it conflict image with hugo?

**Comment by TinoGuo** [comment]
@HEIGE-PCloud nothing difference when trigger these 3 cases, just run and screenshot, all the configurations are the same. from my POV, it seems the configuration was changed in runtime in 3rd case, even though it read as map before, but the configuration was changed to String when process the `image.html`

**Comment by TinoGuo** [comment]
I think I figured out the RC, so I added below to my site as `seo.en.yaml` and `seo.zh-cn.yaml`
```toml
# Site SEO config
# 网站 SEO 配置
[seo]
  # image URL
  # 图片 URL
  image = "/images/Apple-Devices-Preview.png"
  # thumbnail URL
  # 缩略图 URL
  thumbnailUrl = "/images/screenshot.png"
  # Google 搜索结果中网站备用名字
  # alternate site name in Google search result
  # https://developers.google.com/search/docs/appearance/site-names#alternative
  # alternateName = ["Hugo DoIt"]
```

so whenever, I attach `image` field then it will be high possibility fail. If I remove the field, then nothing went wrong. But I have no idea, why the `seo` can override the `image` in params, it could be hugo issue

**Comment by HEIGE-PCloud** [comment]
The SEO config is under the params namespace https://github.com/search?q=repo%3AHEIGE-PCloud%2FDoIt%20params.seo&type=code 

So it should be placed in `params.yaml`. Inside `params.yaml`, you should have both

```yaml
image:
  cacheRemote: true
  optimise: true

seo:
  image: /images/Apple-Devices-Preview.png
  thumbnailUrl: /images/screenshot.png
```

https://github.com/HEIGE-PCloud/DoIt/blob/98ba1e54897e1c903d57e76f0af68ae01dc2a82e/exampleSite/config/_default/params.toml#L543

I am not sure whether this is the RC though.
