### ISSUE TITLE
Q: Customize dark theme CSS

### ISSUE THREAD

**Issue by flobernd** [HEIGE-PCloud/DoIt#1288]
Hi @HEIGE-PCloud,

currently migrating from LoveIt to DoIt. Previously we had variables for both, light- and dark-theme. For example `background-color` and `background-color-dark`.

Could you please tell me what's the new preferred way to customize both themes in the `overrides.scss`?

Thanks!

**Comment by HEIGE-PCloud** [comment]
We are in the process of integrating with Tailwind CSS for better maintainability.

We use CSS variables to manage colors. https://github.com/HEIGE-PCloud/DoIt/blob/0a0b127ebfe518f0fdd63d553ae14798bb94f27d/assets/css/tailwind.css#L29-L228

So if you would like to change the color palette, you can override specific CSS variable in `_override.scss`. You might need to fight the specificity though.

```css
:root {
  --code-background-color: white !important;
}
html.dark {
  --code-background-color: black !important;
}
```
