### ISSUE TITLE
如何让某个单独的页面 page.header.number **不开启**标题自动编号?

### ISSUE THREAD

**Issue by xiaobinqt** [HEIGE-PCloud/DoIt#1334]
### Describe the bug 描述你遇到的错误

我有个页面不想让 page.header.number 生效，不想 开启标题自动编号，请问该如何设置？
我尝试 page.header.number : false 但是不能生效。

**Comment by HEIGE-PCloud** [comment]
In the front matter

```yaml
header:
  number: 
    enable: false
```
