### ISSUE TITLE
[BUG] .Site.Author and .Site.IsMultiLingual removed in v0.136.1

### ISSUE THREAD

**Issue by jamesdeluk** [HEIGE-PCloud/DoIt#1370]
### Describe the bug 描述你遇到的错误

Theme broken as .Site.Author and .Site.IsMultiLingual have been removed

### Expected behavior 期待的行为

Theme to buid

### Screenshots 屏幕截图

![image](https://github.com/user-attachments/assets/6743c58a-3d85-4ea7-9f88-832e27e12760)

### Build Environment 构建环境

hugo-extended 0.136.1

**Comment by HEIGE-PCloud** [comment]
Upgrade your DoIt version, this has already been fixed.

You need to migrate the author config manually, see

https://github.com/HEIGE-PCloud/DoIt/blob/dd1ec9e11b386e040cd6e3f68f19a9ce92102873/exampleSite/config/_default/params.toml#L31-L36

**Comment by SunVdong** [comment]
Same problem
![image](https://github.com/user-attachments/assets/07d78f80-9a29-4359-85f4-ad94aebfecc9)

**Comment by HEIGE-PCloud** [comment]
> Same problem ![image](https://private-user-images.githubusercontent.com/5692188/385710449-07d78f80-9a29-4359-85f4-ad94aebfecc9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE1MDc2OTYsIm5iZiI6MTczMTUwNzM5NiwicGF0aCI6Ii81NjkyMTg4LzM4NTcxMDQ0OS0wN2Q3OGY4MC05YTI5LTQzNTktODVmNC1hZDk0YWViZmVjYzkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTExMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMTNUMTQxNjM2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MWQ5M2RmY2UxZjUzNzMwNzM4Nzc4ZWM3MjQzZDM4MTc1N2U5YmQ2YTA1NzZmNTg4ZjZmYjU3ZGJjNzJkY2U4YSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.GpTt4rn85HLJ0-btKSb7svKHohLS-J0WzSUri3ysTLY)

Update your DoIt version

```
cd themes/DoIt
git pull origin main
cd ../..
git add .
git commit -m "Update DoIt"
```

**Comment by SunVdong** [comment]
```
steps:
      - uses: actions/checkout@v4
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: 'latest'
          extended: true

      - name: Build
        run: hugo --minify
```
Hugo build and deploy workflow  like this. `submodules: true`   ：maybe  DoIt version has been updated.
