### ISSUE TITLE
[BUG] github action deploy failed

### ISSUE THREAD

**Issue by dre4merp** [HEIGE-PCloud/DoIt#1389]
### Describe the bug 描述你遇到的错误

github action deploy failed

### Expected behavior 期待的行为

github action deploy success

### Screenshots 屏幕截图

![image](https://github.com/user-attachments/assets/1f78b66e-1169-4d28-9d85-c4af250b74c6)

### Build Environment 构建环境

the latest commit  [2349f8f](https://github.com/HEIGE-PCloud/DoIt/commit/2349f8f660d5a367d44498f6696515a1d335a0be)

### Additional Information 补充信息

``` yml
name: deploy

on:
    push:
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        concurrency:
            group: ${{ github.workflow }}-${{ github.ref }}
        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                  submodules: true
                  fetch-depth: 1

            - name: Setup Hugo
              uses: peaceiris/actions-hugo@v3
              with:
                  hugo-version: 'latest'
                  extended: true

            - name: Build Web
              run: hugo --minify

            - name: Deploy Web
              uses: peaceiris/actions-gh-pages@v3
              with:
                  PERSONAL_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
                  EXTERNAL_REPOSITORY: dre4merp/dre4merp.github.io
                  PUBLISH_BRANCH: master
                  PUBLISH_DIR: ./public
                  commit_message: ${{ github.event.head_commit.message }}
```
