### ISSUE TITLE
[BUG] mermaid and lightgallery don't work

### ISSUE THREAD

**Issue by dre4merp** [HEIGE-PCloud/DoIt#1391]
## mermaid 
It works locally, but faild by github action.
## lightgallery 
config entry is true, but doesn't work.

### Expected behavior 期待的行为

mermaid and lightgallery work successfully

### Screenshots 屏幕截图

![image](https://github.com/user-attachments/assets/3008ad9f-d271-4a0a-b86d-772e1de446f8)

## Local 
- OS : Windows 10
- hugo : v0.139.3
## github action
- OS : ubuntu-lateset
- hugo : v0.139.3
``` yml
name: deploy

on:
    push:
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        concurrency:
            group: ${{ github.workflow }}-${{ github.ref }}
        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                  submodules: true
                  fetch-depth: 0

            - name: Setup Hugo
              uses: peaceiris/actions-hugo@v3
              with:
                  hugo-version: '0.139.3'
                  extended: true

            - name: Build Web
              run: hugo --minify

            - name: Deploy Web
              uses: peaceiris/actions-gh-pages@v3
```

### Preview Environment 预览环境

- OS: Win 10 
- Browser : Chrome

### Additional Information 补充信息

``` toml
[params]
  [params.page]
    lightgallery = true
```
