### ISSUE TITLE
[BUG] Left/right margin for code blocks

### ISSUE THREAD

**Issue by PumpkinDemo** [HEIGE-PCloud/DoIt#1415]
### Describe the bug 描述你遇到的错误

A code block displayed on a page without line numbers has no left/right margin. I don't know if this is a feature or a bug. If it's a feature, where can I configure its behaviors?

<img width="883" alt="截屏2024-12-29 16 10 19" src="https://github.com/user-attachments/assets/e12426a2-9ba2-411e-98ba-a6949376d5b0" />

I want it displayed as in the [demo site](https://hugodoit.pages.dev/theme-documentation-content/):

<img width="817" alt="截屏2024-12-29 16 11 27" src="https://github.com/user-attachments/assets/b7227d56-6823-4f17-a822-ec35a18236d3" />

I find that the code lines with margin consist of `<span class="line">` and `<span class="cl">`:

<img width="437" alt="截屏2024-12-29 16 23 06" src="https://github.com/user-attachments/assets/24173b9d-ef3d-4ffc-aa5e-7b12caa5801b" />

But in the problematic case, code lines are `<span style="display:flex;">` and `<span>`:

<img width="431" alt="截屏2024-12-29 16 15 08" src="https://github.com/user-attachments/assets/9d014604-d404-469c-b58e-5894dfa79b9d" />

I searched the source code of the Doit theme repo but could not find anything related.

### Expected behavior 期待的行为

Code blocks displayed without line numbers should have left/right margins

### Build Environment 构建环境

- OS: MacOS
- Theme Version: commit 9b6202d74f52199780ac6903ac6695912394230a, branch main
- Hugo version: hugo v0.140.1+extended+withdeploy darwin/amd64 BuildDate=2024-12-23T16:26:35Z

### Preview Environment 预览环境

- OS: MacOS
- Browser: Chrome 131.0.6778.70

**Comment by PumpkinDemo** [comment]
```toml
[markup]
  # Syntax Highlighting (https://gohugo.io/content-management/syntax-highlighting)
  [markup.highlight]
    # false is a necessary configuration (https://github.com/dillonzq/LoveIt/issues/158)
    noClasses = false
```

I find this missed in my configuration.
