### ISSUE TITLE
[BUG] `lineNos` in hugo.yaml doesn't work

### ISSUE THREAD

**Issue by PumpkinDemo** [HEIGE-PCloud/DoIt#1416]
### Describe the bug 描述你遇到的错误

The `lineNos` option in hugo.yaml doesn't work:

```yaml
markup:
  highlight:
    lineNos: false
    noClasses: false
    codeFences: true
    guessSyntax: false
```

I find the template `doit/layouts/_default/_markup/render-codeblock.html` does not reference this option. It only uses the option provided by the code block.
```hugo
{{- $lineNos := cond (eq .Options.linenos false) "" "show-line-numbers" -}}
```

### Expected behavior 期待的行为

The `lineNos` option in hugo configuration files should be effective for users to control the line numbers of code blocks globally.

**Comment by HEIGE-PCloud** [comment]
It's not possible https://discourse.gohugo.io/t/how-to-get-sites-markup-configuration-in-template/42394

**Comment by HEIGE-PCloud** [comment]
We can add a separate global toggle but that might be confusing...

**Comment by PumpkinDemo** [comment]
In my local solution, I have added an additional option in `params`:

```yaml
params:
  page:
    code:
      lineNos: false
```

and modify the template as following to make it use the global option.

```hugo
{{- $lineNos := cond (eq .Options.linenos false) "" (cond (eq site.Params.page.code.lineNos false) "" "show-line-numbers") -}}
```

Additional configuration options bring confusion, indeed. But for those who want a default "no line numbers", I hope this can help.
