### ISSUE TITLE
[BUG] Unable to get Table of Contents working

### ISSUE THREAD

**Issue by BradKnowles** [HEIGE-PCloud/DoIt#1444]
### Describe the bug 描述你遇到的错误

I am porting my site from LoveIt to DoIt, and seem unable to get the Table of Contents to work.  I've put this is my `config.toml` (I've not renamed it to `hugo.toml` yet).

```toml
[params.page.toc]
  # whether to enable the table of the contents
  enable = true
  # whether to make the table of the contents in the sidebar automatically collapsed
  auto = false
```

Originally I had a separate `params.toml` file but putting the options there also doesn't seem to work.

In fact, none of my `params.page` settings work.

```toml
[params.page.toc]
  # whether to enable the table of the contents
  enable = true
  # whether to make the table of the contents in the sidebar automatically collapsed
  auto = false

[params.page.code]
  # whether to show the copy button of the code block
  copy = false
  # the maximum number of lines of displayed code by default
  maxShownLines = -1

[params.page.share]
  enable = true
  Twitter = true
  Facebook = true
  Linkedin = true
  HackerNews = true
  Reddit = true
  Instapaper = true
  Pocket = true
```

### Expected behavior 期待的行为

I see table of contents working on the documentation site, so I'm looking for something similar.

### Preview Environment 预览环境

`hugo server --disableFastRender --buildDrafts --buildFuture --enableGitInfo --ignoreCache`

Windows 11

### Additional Information 补充信息

hugo v0.144.2-098c68fd18f48031a7145bedab30cbaede48858f+extended windows/amd64 BuildDate=2025-02-19T12:17:04Z VendorInfo=gohugoio

**Comment by HEIGE-PCloud** [comment]
This is likely due to a configuration error somewhere, please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) so we can investigate further. Thanks.

**Comment by HEIGE-PCloud** [comment]
We temporarily close this due to the lack of enough information. Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue. Thanks.

**Comment by BradKnowles** [comment]
You can find the reproduction [here](https://github.com/BradKnowles/hugo-doit-toc).

It stems from my, probably incorrectly and against conventions, renaming the `posts` directory to `blog` because I wanted my urls to be `https://example/blog/first_post` instead of `https://example/posts/first_post`.

**Comment by HEIGE-PCloud** [comment]
I think you will have to place your posts in the `posts` directory. The `posts` directory is special since it contains a special template for articles that enables TOC https://github.com/HEIGE-PCloud/DoIt/blob/deaf0c8a98ebf5294d537d5ba2d88bb2b4d62ab9/layouts/posts/single.html

This behaviour is inherited from the LoveIt theme, so I expect the TOC not working there either.

For your use case, it's possible to store the content in a filesystem path while serving them under a different URL path, see this example: https://gohugo.io/content-management/urls/#permalinks-monolingual-examples

So in your case, adding 

```toml
[permalinks]
  [permalinks.page]
    posts = '/blog/:slug/'
  [permalinks.section]
    posts = '/blog/'
```

to `config.toml` should do the trick.
