### ISSUE TITLE
[BUG] 在执行hugo serve命令时，在public文件夹下，只为每个series和categories生成了.xml文件，但是没有生成.html文件。在github pages部署后，每个series下显示的是xml文件，而不渲染好的html文件。

### ISSUE THREAD

**Issue by wengao59** [HEIGE-PCloud/DoIt#1478]
### Describe the bug 描述你遇到的错误

前两天博客的series和categories还是正常输出，从今天开始出现的如下情况。

我在本地运行`hugo serve`时，输出中有如下报错：WARN  found no layout file for "html" for kind "term": You should create a template file which matches Hugo Layouts Lookup Rules for this combination.

在输出的public文件夹中，各个文章的html文件输出正常，但是对于各个categories和series，只输出了.xml文件，未输出.html文件。

在用github pages部署后，网页显示：This XML file does not appear to have any style information associated with it. The document tree is shown below. 输出的也是类似于sitemap.xml文件的样式，无法输出html文件（因为public下没有html文件）

### Expected behavior 期待的行为

期待public文件夹下能够输出html文件，网页能够正常输出渲染后的html。

### Screenshots 屏幕截图

public文件夹下各个categories和series输出如下：
![Image](https://github.com/user-attachments/assets/272d9af2-bf83-4e95-b4b2-628f6bc47771)

![Image](https://github.com/user-attachments/assets/04db1f44-bef9-463f-8fa9-5d5dea5eb7f6)

github pages部署后输出如下：

![Image](https://github.com/user-attachments/assets/6ff33173-b402-40f7-a3e3-80cf447e4fa6)

### Build Environment 构建环境

我本地所使用的node版本是v18.17.1，DoIt是用的最新版本（使用git submodule添加到项目中），本地使用的是hugo-extended生成。

我使用的github workflow如下：

```yaml
# name: deploy github pages # 名字自取

# on:
#   push:
#     branches:
#       - main # 这里的意思是当 main分支发生push的时候，运行下面的jobs，这里先改为github-actions

# jobs:
#   deploy: # 任务名自取
#     runs-on: ubuntu-latest # 在什么环境运行任务
#     steps:
#       - uses: actions/checkout@v2 # 引用actions/checkout这个action，与所在的github仓库同名
#         with:
#           submodules: true # Fetch Hugo themes (true OR recursive) 获取submodule主题
#           fetch-depth: 0 # Fetch all history for .GitInfo and .Lastmod

#       - name: Setup Hugo # 步骤名自取
#         uses: peaceiris/actions-hugo@v2 # hugo官方提供的action，用于在任务环境中获取hugo
#         with:
#           hugo-version: "latest" # 获取最新版本的hugo
#           extended: true

#       - name: Build
#         run: hugo --minify # 使用hugo构建静态网页

#       - name: Deploy
#         uses: peaceiris/actions-gh-pages@v4 # 一个自动发布github pages的action
#         with:
#           github_token: ${{ secrets.GITHUB_TOKEN }} 该项适用于发布到源码相同repo的情况，不能用于发布到其他repo
#           # external_repository: salvely/salvely.github.io # 发布到哪个repo
#           # personal_token: ${{ secrets.ACTION_ACCESS_TOKEN }} # 发布到其他repo需要提供上面生成的personal access token
#           publish_dir: ./public # 注意这里指的是要发布哪个文件夹的内容，而不是指发布到目的仓库的什么位置，因为hugo默认生成静态网页到public文件夹，所以这里发布public文件夹里的内容
#           publish_branch: gh-pages # 发布到哪个branch

name: GitHub Pages

on:
  push:
    branches:
      - main # Set a branch to deploy
  pull_request:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-22.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0 # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: "latest"
          extended: true

      - name: Build
        run: hugo --minify

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public

```

### Additional Information 补充信息

请问我是缺了什么依赖包吗？还是主题更新了？我今天调了一天，不知道该怎么办，尝试了各种方法，但是依然存这些情况。我能描述的只有这么多了，如果能麻烦您帮忙看看的话，就太谢谢了！
