### ISSUE TITLE
[FEATURE] Enable FUSE Search to Include content Field

### ISSUE THREAD

**Issue by yewentao256** [HEIGE-PCloud/DoIt#1479]
### Describe the feature you want 描述你的功能需求

Hi, thank you for your great work on this project!

Currently, the FUSE search engine in DoIt only searches through the title field of content. It does not support searching within the content field, which limits the discoverability of posts based on their full text.

### Useful reference 有价值的参考

Would it be possible to support full-text search within the content field as well? Ideally, this could be done through a configuration option to enable content field indexing for FUSE?

```js
var fuseOptions = {
  keys: [
    { name: "title", weight: 0.8 },
    { name: "content", weight: 0.5 },
    { name: "tags", weight: 0.3 },
    { name: "categories", weight: 0.3 }
  ],
```

This would significantly enhance the user experience, especially for users with long-form content who rely on detailed search functionality.

Looking forward to your thoughts — and happy to help test if needed!

Thanks again 🙏

**Comment by HEIGE-PCloud** [comment]
I am pretty sure that Fuse.js does a full text search on an index that looks like this https://hugodoit.pages.dev/index.json

https://github.com/HEIGE-PCloud/DoIt/blob/593e594a00701aebcded9c451ec846d287483d95/assets/js/theme.ts#L422

**Comment by yewentao256** [comment]
Thanks for answering!

My configuration now is:

```toml
[outputs]
  home = ["HTML", "RSS", "JSON"]
  page = ["HTML", "MarkDown"]
  section = ["HTML", "RSS"]
  taxonomy = ["HTML", "RSS"]
  [params.search]
    enable = true
    # type ("algolia" (third party service), "fuse")
    type = "fuse"
    # maximum content length of the search index
    contentLength = 4000
    placeholder = "search here"
    maxResultLength = 10
    # {{< version 0.2.3 >}} snippet length for search results
    snippetLength = 50
    # {{< version 0.2.1 >}} HTML tag used to highlight search results
    highlightTag = "em"
    # {{< version 0.2.4 >}} Whether to use baseURL-based absolute paths in the search index
    absoluteURL = false
    [params.search.algolia]
      index = ""
      appID = ""
      searchKey = ""
    [params.search.fuse]
      # {{< version 0.2.12 >}} https://fusejs.io/api/options.html
      isCaseSensitive = false
      minMatchCharLength = 2
      findAllMatches = false
      location = 0
      threshold = 0.3
      distance = 100
      ignoreLocation = false
      useExtendedSearch = false
      ignoreFieldNorm = false
```

Could you please tell me how to configure and enable the content search?
