### ISSUE TITLE
[FEATURE] Different Style for TOC

### ISSUE THREAD

**Issue by HEIGE-PCloud** [HEIGE-PCloud/DoIt#23]
The `max-width: 800px` setting on the article element leaves a lot of blank space on a wide screen. The position and margin of TOC and article need some redesigns.

Different styles can be left as a setting which can be switched by the user manually for each post or entire site, or it can be adjusted by the reader with a button.

**Comment by HEIGE-PCloud** [comment]
## Possible layout 1

![image](https://user-images.githubusercontent.com/52968553/116002210-88282b00-a5f0-11eb-8191-616dbde3a21f.png)

```css
.page {
    margin-left: 10%;
    margin-right: auto;
    max-width: initial;
    width: 70%;
}
```

**Comment by HEIGE-PCloud** [comment]
## Possible layout 2

![image](https://user-images.githubusercontent.com/52968553/116003323-60879180-a5f5-11eb-97bf-8c8500b5fed9.png)

```css
.page {
    margin-left: 324px;
    margin-right: auto;
    max-width: initial;
    width: 70%;
}
.toc-auto {
    right: 1168px;
    max-width: 328px;
    visibility: visible;
    position: fixed;
    top: 76px;
}
```
