### ISSUE TITLE
[FEATURE] URL路径规范建议

### ISSUE THREAD

**Issue by ghost** [HEIGE-PCloud/DoIt#299]
### URL路径规范建议

- 建议保持 Hugo 的URL的默认路径构成
  如：https://hugodoit.pages.dev/markdown-tests/
  改为：https://hugodoit.pages.dev/posts/markdown-tests/
  因为文章都是放在 posts/ 目录下的。同时一些用户要想更换主题为 DoIt 时，由于URL路径不统一规范，导致该用户在迁移主题时要大量修改原有文章中内嵌的本站内的其他文章的URL。
  这个需求值得规范，我希望这个功能解决 ...

**Comment by HEIGE-PCloud** [comment]
这并不是一个规范问题，不同的用户想要用不同的方式管理文章 URL。有些用户希望直接使用文章标题，有些希望使用 posts/文章标题，有些希望 年月日/文章标题。所以 Hugo 提供了 Permalinks 的自定义配置选项。在 config.toml 中，修改如下配置即可。

```toml
# Permalinks config (https://gohugo.io/content-management/urls/#permalinks)
# Permalinks 配置 (https://gohugo.io/content-management/urls/#permalinks)
[Permalinks]
  # posts = ":year/:month/:filename"
  posts = "posts/:filename"
```

更一般的，相比于直接使用 URL 链接来指向其他文章，使用 Hugo 内建的 [ref 和 relref](https://gohugo.io/content-management/shortcodes/#ref-and-relref) shortcode 来创建链接将使得管理更加方便。
