### ISSUE TITLE
[FEATURE] 建议修改目录标题前的 # 号

### ISSUE THREAD

**Issue by ghost** [HEIGE-PCloud/DoIt#300]
### 建议修改目录标题前的 # 号，改成其他符号，因为#号可能会与其他内容的含义冲突。以及页面右侧的目录中显示的符号保持一致。
<img width="490" alt="Screenshot 2021-10-27 at 15 27 53" src="https://user-images.githubusercontent.com/29486126/139020378-31009c85-685f-4702-8189-5ff19707b64c.png">

<img width="301" alt="Screenshot 2021-10-27 at 15 28 30" src="https://user-images.githubusercontent.com/29486126/139020388-772bc50a-a718-4b78-9f42-04395243a26f.png">

### 建议参考：https://hugo-theme-even.netlify.app

<img width="199" alt="Screenshot 2021-10-27 at 15 36 04" src="https://user-images.githubusercontent.com/29486126/139020914-ee89fdc3-520d-4839-b48f-2180628d980a.png">

**Comment by HEIGE-PCloud** [comment]
全部统一为了 `|` https://github.com/HEIGE-PCloud/DoIt/commit/baef943c332adf20eb4b923145deb7c9e9392882

**Comment by eyllanesc** [comment]
@HEIGE-PCloud  It would be great if that sign is configurable.

**Comment by HEIGE-PCloud** [comment]
@eyllanesc It is indeed customizable... The sign is set by CSS, so you can create [custom CSS](https://hugodoit.pages.dev/theme-documentation-basics/#33-style-customization) to change it to whatever you like.

In `your_site\assets\css\_custom.scss`, add the following

```css
.single {
    .content {
        > h2 > .header-mark::before {
            font-family: "Font Awesome 5 Free";
            content: "\f0c1";
        }
    }
}
```

will change the sign before all h2 tags in single posts.

![image](https://user-images.githubusercontent.com/52968553/139245299-71274829-186e-46ec-a181-4bc4eb6ff99d.png)
