### ISSUE TITLE
[BUG] Comments are not visible

### ISSUE THREAD

**Issue by rolandjitsu** [HEIGE-PCloud/DoIt#554]
### Describe the bug 描述你遇到的错误

It seems like the comments area is not displayed after enabling it.

You can view my config at [rolandjitsu/rolandsdev.blog/config.yaml#L162](https://github.com/rolandjitsu/rolandsdev.blog/blob/628048b1856c5a91ab74383e9aaf88e0c685b75d/config.yaml#L162) and the blog at [rolandsdev.blog](https://rolandsdev.blog/).

### Expected behavior 期待的行为

I should be able to view the comments and add new comments.

### Build Environment 构建环境

- netlify, Linux
- doit b73c6f5342157d2cb3448a2e20c5b5e7eb9334bb
- hugo v0.94.2-48FB9E4D+extended linux/amd64

### Preview Environment 预览环境

- macOS 11.6.2
- Chrome 99.0

**Comment by rolandjitsu** [comment]
My bad :laughing: I forgot to enable the parent comment section. It looks great! (though, for giscus, the theming doesn't match).

**Comment by Meyerclex** [comment]
😥Meet the same bug too. The system I used is Waline. But I could see your comment below the article, did you solve that?

**Comment by rolandjitsu** [comment]
@Meyerclex it turns out I just missed a config.

Before:
```yaml
params:
  ...
  page:
    ...
    comment:
      giscus:
        enable: yes
        ...
```

After:
```yaml
params:
  ...
  page:
    ...
    comment:
      enable: yes
      giscus:
        enable: yes
        ...
```

But it's a little confusing to allow many comment systems at the same time 😕 I'd imagine most users would use a single one? 🤷 

In any case, I'm loving how easy it is to configure all that!
