### ISSUE TITLE
[BUG] DevTools failed to load source map

### ISSUE THREAD

**Issue by stimw** [HEIGE-PCloud/DoIt#584]
----Update ↓----
It even appears on the DoIt official demo site...
----Update ↑----

### Describe the bug 描述你遇到的错误

Hello, I met this error whether on LoveIt or DoIt:

The Chrome says: 
DevTools failed to load source map: Could not load content for http://localhost:1313/sm/5d8a97cdb40a6c49031b52d63494a6eca084416b5b035e5698fdc5fa0969b2c3.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE

### Expected behavior 期待的行为

no error

### Screenshots 屏幕截图

<img width="1719" alt="image" src="https://user-images.githubusercontent.com/30977647/165252692-88ffcd2e-3e46-4b3a-80b2-911847513322.png">

### Build Environment 构建环境

- OS/Platform: MacOS / Vercel
- Hugo version: hugo v0.97.3+extended
- Theme version: latest

### Preview Environment 预览环境

- OS: MacOS
- Browser: Chrome

### Additional Information 补充信息

In `config.toml`, I try to only keep the settings below:

```toml
baseURL = "./"
defaultContentLanguage = "en"
languageCode = "en"
title = "xxx"
theme = "DoIt

[params]
  description = "xxx"
  keywords = ["xxx"]
  version = "0.2.X"
```

It shows the error, too.

When I set 
```toml
[params.page.table]
  sort = true
```
I get another map loss:

DevTools failed to load source map: Could not load content for http://localhost:1313/sm/0ae2d60f74d4da035e6093a3059d17f56306a059fee7bbce514325c0576211bf.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
