### ISSUE TITLE
文章日期错误

### ISSUE THREAD

**Issue by wowow005** [HEIGE-PCloud/DoIt#590]
### Describe the bug 描述你遇到的错误

在主页显示的日期和文章页面的日期显示错误,  不知道是怎么回事.

### Screenshots 屏幕截图

![image](https://user-images.githubusercontent.com/61683315/165989392-c7a445bf-e2e3-40cd-a13b-9978a2f8c078.png)

![image](https://user-images.githubusercontent.com/61683315/165989432-04bc8818-c878-40c6-b2c8-b464ace9b287.png)

### Build Environment 构建环境

hugo v0.95.0-DEV+extended darwin/arm64 BuildDate=unknown
GOOS="darwin"
GOARCH="arm64"
GOVERSION="go1.17.8"

### Preview Environment 预览环境

- OS: Mac
- Chrome

### Additional Information 补充信息

应该是和我改了 config.toml 有关.

和这个日期相关的配置是不是只有 `params.section`?

``` toml
[params.section]
  paginate = 20
  dateFormat = "01-02"
  rss = 10
  # DoIt 新增 | 0.2.13 最近更新文章设置
  [params.section.recentlyUpdated]
    enable = false
    rss = false
    days = 30
    maxCount = 10
```
