### ISSUE TITLE
(new) google-analytics doesn't work?

### ISSUE THREAD

**Issue by Thanatermesis** [HEIGE-PCloud/DoIt#612]
I just created a google analytics account for my new blog and the code is not UA-XXXXXXXX-X but instead G-XXXXXXXXXX (new system? I don't see how to get the UA version), it doesn't seems to count my first visits, is this change the cause of it?

**Comment by HEIGE-PCloud** [comment]
<img width="1080" alt="image" src="https://user-images.githubusercontent.com/52968553/168554668-5109c966-af00-4117-b8ab-a756083a56fd.png">

It is working on my side.

https://github.com/HEIGE-PCloud/DoIt/blob/326f5aae7f8bb49206ce3009c0353cd6074b6130/layouts/partials/plugin/analytics.html#L3-L11

The config for ga is the one to config the new G-XXXXXXXXXX id.

Check:
1. Whether you have enabled it correctly
```toml
  [params.analytics]
    enable = true
    # Google Analytics
    [params.analytics.google]
      id = "G-XXXXXXXXXX"
```
2. Whether your browser block analytics somehow.
