### ISSUE TITLE
[FEATURE] 懒加载布局偏移

### ISSUE THREAD

**Issue by 713b76b7-2247-4bd5-98a7-014226363f9b** [HEIGE-PCloud/DoIt#847]
### Describe the feature you want 描述你的功能需求

懒加载布局偏移的问题，在图片加载前，图片占据高度为 0，而图片加载后，图片占据高度可能会发生变化，从而导致布局偏移。

### Useful reference 有价值的参考

用两层div容器，类似下面的代码：

```css
.fiximg {
  position: relative;
  display: block;
  overflow: hidden;
  background-color: var(--color-wrapper);
  width: 100%;

  &__container {
    display: block;
    width: 100%;
    height: 0;
    margin: 0;
    padding-bottom: '<ASPECT RATIO HERE>';

    img {
      display: block;
      width: 100%;
      margin: 0;
      color: var(--color-primary);
      font-size: inherit;
      text-align: center;
    }
  }
}
```

背景颜色甚至可以搭配hugo在v0.104.0推出的[colors选项](https://gohugo.io/content-management/image-processing/#colors)，实现类似 https://arc.sped0nwen.com 的懒加载效果。

 目前我还在尝试，不过我看作者您的图片处理管线比较长，可能需要一定时间，如果写出来之后我会提个pr。
