### ISSUE TITLE
[FEATURE] Make CDN config accept both relative URL and absolute URL

### ISSUE THREAD

**Issue by evilpan** [HEIGE-PCloud/DoIt#946]
### Describe the feature you want 描述你的功能需求

Currently the cdn config only accept single `prefix` with multiple `libFiles` and concat them. However, lots of the CDN may miss some resource while other CND miss other resources.

For example, the cdn `npm.elemecdn.com` has all the libFiles, but miss fonts like `https://npm.elemecdn.com/@fortawesome/fontawesome-free@5.13.0/webfonts/fa-brands-400.ttf`; and the cdn `code.bdstatic.com` has lots of libFiles but miss the `Valine.js` repo.

Maybe it's a good idea to accept absolute URL for cdn.yml file, incase we want to config only one or two of the links in the same file with another prefix. 

For example:

```yml
prefix:
  libFiles: https://code.bdstatic.com/npm/
libFiles:
  twemojiJS: twemoji@13.0.0/dist/twemoji.min.js
  typeitJS: typeit@7.0.4/dist/typeit.min.js
  valineJS: https://npm.elemecdn.com/valine@1.5.1/dist/Valine.min.js
```
