### ISSUE TITLE
[FEATURE] Inline logo image in header?

### ISSUE THREAD

**Issue by C-Duv** [HEIGE-PCloud/DoIt#980]
### Describe the feature you want 描述你的功能需求

I would like the image set by `params.header.title.logo` to be (optionally) inline.

That way I can have a image logo **and** some text alongside.

### Useful reference 有价值的参考

The following produces a 2-line header I would rather have image and text on the same line:

```yaml
params:
  header:
    title:
      logo: https://hugodoit.pages.dev/images/avatar.webp
      post: DoIt
```

![image](https://github.com/HEIGE-PCloud/DoIt/assets/1466273/d2327ad1-31d0-4a09-af6b-1f135f1e21bf)
