### ISSUE TITLE
[FEATURE] Dark mode avatar

### ISSUE THREAD

**Issue by jamesdeluk** [HEIGE-PCloud/DoIt#981]
### Describe the feature you want 描述你的功能需求

My avatar is black, meaning when I activate dark mode, it disappears.

It would be useful to have an option where you can set a different avatar for dark mode.

**Comment by HEIGE-PCloud** [comment]
In this case, I recommend adding some custom CSS to adjust the colour. Create the file `your_site/assets/css/_custom.scss` if it does not exist, then add the following to it

```scss
.home-avatar img, .logo {
  [theme="dark"] &,
  [theme="black"] & {
    filter: invert(1.0);
  }
}
```

should do.
