### ISSUE TITLE
[BUG] 0.4.0配置和之前的版本有什么区别吗

### ISSUE THREAD

**Issue by bwcxyk** [HEIGE-PCloud/DoIt#995]
### Describe the bug 描述你遇到的错误

还有主题demo网站被反电信诈骗拦截了
![image](https://github.com/HEIGE-PCloud/DoIt/assets/28802427/d1a33c40-a0a4-4796-8e66-2ce9ecf258e2)

**Comment by 713b76b7-2247-4bd5-98a7-014226363f9b** [comment]
### 配置文件区别

https://github.com/HEIGE-PCloud/DoIt/commit/7a1dbad9d1300e8041390a40fb774e1d59255959

当然你用旧版本的也不是不行，只是新版本的管理方式更加原子化而已。

### 网站拦截

<img width="1512" alt="image" src="https://github.com/HEIGE-PCloud/DoIt/assets/70063177/f0ea02d4-c5cc-4fb4-9a32-63c9a3270681">

无法复现

**Comment by bwcxyk** [comment]
> ### 配置文件区别
> [7a1dbad](https://github.com/HEIGE-PCloud/DoIt/commit/7a1dbad9d1300e8041390a40fb774e1d59255959)
> 
> 当然你用旧版本的也不是不行，只是新版本的管理方式更加原子化而已。
> 
> ### 网站拦截
> <img alt="image" width="1512" src="https://user-images.githubusercontent.com/70063177/248525547-f0ea02d4-c5cc-4fb4-9a32-63c9a3270681.png">
> 无法复现

部分区域
![image](https://github.com/HEIGE-PCloud/DoIt/assets/28802427/9142b9ea-19c7-488d-8784-8c44255dd167)

**Comment by 713b76b7-2247-4bd5-98a7-014226363f9b** [comment]
ISP拦截的话没什么办法

**Comment by bwcxyk** [comment]
> ### 配置文件区别
> [7a1dbad](https://github.com/HEIGE-PCloud/DoIt/commit/7a1dbad9d1300e8041390a40fb774e1d59255959)
> 
> 当然你用旧版本的也不是不行，只是新版本的管理方式更加原子化而已。
> 

themesDir配置后一直无法找到主题目录，这个如何排查配置的目录指向是什么。

**Comment by 713b76b7-2247-4bd5-98a7-014226363f9b** [comment]
溯源你现在的`themeDir`话不太清楚，可以试试加个`--verbose`参数？

具体的流程可以参考CI，就gh-action里那个`build.yml`，不过这套CI都没动过，你从v0.3到v0.4不该出什么问题的。

如果还是不行可以去看看hugo文档里关于`themeDir`的说明和issue

**Comment by bwcxyk** [comment]
> 溯源你现在的`themeDir`话不太清楚，可以试试加个`--verbose`参数？
> 
> 具体的流程可以参考CI，就gh-action里那个`build.yml`，不过这套CI都没动过，你从v0.3到v0.4不该出什么问题的。
> 
> 如果还是不行可以去看看hugo文档里关于`themeDir`的说明和issue

0.3配置的是`themesDir = "themes"`
同样配置的话
![image](https://github.com/HEIGE-PCloud/DoIt/assets/28802427/d9e68827-09c5-40e0-ad55-f1ab397c736b)

**Comment by 713b76b7-2247-4bd5-98a7-014226363f9b** [comment]
不清楚你的文件结构

如果你的文件是在`themes/doit`

你的`themesDir`应该是`themes/doit`

单单一个`theme`看起来挺可疑的

**Comment by bwcxyk** [comment]
> themes/doit

`hugo/themes/DoIt`
我单独配置在config.toml就可以
![image](https://github.com/HEIGE-PCloud/DoIt/assets/28802427/1d4a1c2c-ef66-4552-a8a9-24219dc6afea)
![image](https://github.com/HEIGE-PCloud/DoIt/assets/28802427/e71c5152-7aab-4155-ab3c-3b8998052251)

**Comment by 713b76b7-2247-4bd5-98a7-014226363f9b** [comment]
那原先配置不成功时的`hugo.toml`内容是什么呢

**Comment by bwcxyk** [comment]
> > themes/doit

我只是把`config.toml`的配置迁移到了各个配置中，目前来看`config.toml`不能删除，`themesDir`配置在`config.toml`中才能读取到

**Comment by bwcxyk** [comment]
```
# theme
# 主题
theme = "DoIt"
# themes directory
# 主题目录
themesDir = "themes"
```
这一部分内容必须在`config.toml`中，否则都会报错。

**Comment by 713b76b7-2247-4bd5-98a7-014226363f9b** [comment]
![image](https://github.com/HEIGE-PCloud/DoIt/assets/70063177/af47c27a-7b52-4934-87d5-2b65de6262da)

但如果读取不到默认值也是`themes`

晚上的时候我测试一下

同时也建议你看看是不是迁移config的时候哪搞错了，因为并没有其他用户报告类似的问题

**Comment by bwcxyk** [comment]
> 
原因是找不到`theme = "DoIt"`配置

**Comment by 713b76b7-2247-4bd5-98a7-014226363f9b** [comment]
## 测试结果

![Snipaste_2023-06-25_23-04-41](https://github.com/HEIGE-PCloud/DoIt/assets/70063177/3e66de19-f735-4be6-a147-07c6d6d4e04a)

无法复现

## 文件树
```shell
.
├── archetypes
│  └── default.md
├── assets
│  └── jsconfig.json
├── config
│  └── _default
│     ├── author.toml
│     ├── hugo.en.toml
│     ├── hugo.toml
│     ├── hugo.zh-cn.toml
│     ├── markup.toml
│     ├── mediaTypes.toml
│     ├── menu.en.toml
│     ├── menu.zh-cn.toml
│     ├── outputFormats.toml
│     ├── outputs.toml
│     ├── params.en.toml
│     ├── params.toml
│     ├── params.zh-cn.toml
│     ├── permalinks.toml
│     ├── privacy.toml
│     ├── sitemap.toml
│     └── taxonomies.toml
├── content
│  ├── about
│  │  ├── index.en.md
│  │  └── index.zh-cn.md
│  ├── authors
│  │  ├── _index.en.md
│  │  └── _index.zh-cn.md
│  ├── categories
│  │  └── documentation
│  ├── offline
│  │  └── index.en.md
│  ├── posts
│  │  ├── basic-markdown-syntax
│  │  ├── emoji-support
│  │  ├── how-to-DoIt
│  │  ├── pwa-support
│  │  ├── tests
│  │  ├── theme-documentation-basics
│  │  ├── theme-documentation-built-in-shortcodes
│  │  ├── theme-documentation-content
│  │  └── theme-documentation-extended-shortcodes
│  ├── series
│  │  ├── _index.en.md
│  │  ├── _index.zh-cn.md
│  │  ├── getting-start
│  │  ├── how-to-doit
│  │  └── test-series
│  ├── showcase
│  │  ├── index.en.md
│  │  └── index.zh-cn.md
│  └── tags
│     ├── configuration
│     ├── content
│     └── installation
├── data
├── hugo.toml
├── layouts
├── resources
│  └── _gen
│     ├── assets
│     └── images
├── static
└── themes
   └── DoIt
      ├── archetypes
      ├── assets
      ├── CHANGELOG.md
      ├── CODE_OF_CONDUCT.md
      ├── dependencies.json
      ├── exampleSite
      ├── i18n
      ├── images
      ├── layouts
      ├── LICENSE
      ├── package-lock.json
      ├── package.json
      ├── README.md
      ├── README.zh-cn.md
      ├── SECURITY.md
      ├── static
      ├── tailwind.config.js
      └── theme.toml
```

## 配置文件

仅修改`enableGitInfo`和`themesDir`，其他均和`exampleSite`内的一致

```toml
baseURL = "https://hugodoit.pages.dev"
# [en, zh-cn, fr, pl, ...] determines default content language
# [en, zh-cn, fr, pl, ...] 设置默认的语言
defaultContentLanguage = "en"
# theme
# 主题
theme = "DoIt"
# themes directory
# 主题目录
themesDir = "themes"

# website title
# 网站标题
title = "DoIt"

# whether to use robots.txt
# 是否使用 robots.txt
enableRobotsTXT = true
# whether to use git commit log
# 是否使用 git 信息
enableGitInfo = false
# whether to use emoji code
# 是否使用 emoji 代码
enableEmoji = true

# ignore some build errors
# 忽略一些构建错误
# ignoreErrors = ["error-remote-getjson", "error-missing-instagram-accesstoken"]
```
