### ISSUE TITLE
[BUG] 赞赏按钮失效

### ISSUE THREAD

**Issue by yeahwong** [HEIGE-PCloud/DoIt#999]
### Describe the bug 描述你遇到的错误

```
# Sponsor config
# 赞助设置
[sponsor]
  enable = false
  bio = "If you find this post helpful, please consider sponsoring."
  link = "https://github.com/sponsors/HEIGE-PCloud"
  custom = "<a href=\"https://www.buymeacoffee.com/PCloud\" target=\"_blank\"><img src=\"https://cdn.buymeacoffee.com/buttons/v2/default-yellow.png\" alt=\"Buy Me A Coffee\" style=\"height: 40px !important;width: 145 !important;\" ></a>"
```

设置之后，并没有生效？请问这个设置已经不起作用了吗？

**Comment by HEIGE-PCloud** [comment]
在 demo 站上是没问题的 https://hugodoit.pages.dev/theme-documentation-basics/#comments
请问能提供一个最小重现吗？

**Comment by yeahwong** [comment]
> 在 demo 站上是没问题的 https://hugodoit.pages.dev/theme-documentation-basics/#comments 请问能提供一个最小重现吗？

config.toml 是不是要用分开的那种？我还是用着合并的，等我换成分开的，再来回复。

**Comment by 713b76b7-2247-4bd5-98a7-014226363f9b** [comment]
> > 在 demo 站上是没问题的 https://hugodoit.pages.dev/theme-documentation-basics/#comments 请问能提供一个最小重现吗？
> 
> 
> 
> config.toml 是不是要用分开的那种？我还是用着合并的，等我换成分开的，再来回复。

这个没关系的，不需要分开

**Comment by yeahwong** [comment]
> 在 demo 站上是没问题的 https://hugodoit.pages.dev/theme-documentation-basics/#comments 请问能提供一个最小重现吗？

谢谢，我将`[sponsor]`改成`[params.sponsor]`，就成功显示了。不好意思，打扰了，我太菜了。
然后我觉得 sponsor 按钮与上下部分之间的间距有点大，如图所示，是否可以调整小一点呢？

<img width="850" alt="image" src="https://github.com/HEIGE-PCloud/DoIt/assets/5824590/361246f6-9793-40e7-803d-93634b88d485">

**Comment by HEIGE-PCloud** [comment]
你可以修改 `your_site/assets/css/_custom.scss`

```css
.single {
  .sponsor {
    padding-top: 0px;
    .sponsor-custom {
        margin-top: 10px;
        margin-bottom: 10px;
    }
  }
  .post-footer {
    margin-top: 0px;
  }
}

```

来微调行间距。不过由于各种历史遗留问题，有 4 个值会影响它的上下间距。。。
